### ISSUE TITLE
Preparing prescriptions data

### ISSUE THREAD

**Issue by emmavestesson** [ramses-antibiotics/ramses-package#68]
Hi, 

A few questions/things I noticed preparing prescription data for use with Ramses. 

The help file for `daily_frequency()`  says that there are only two valid values -1 and -9, I assume this is in addition to positive integers actually indicating the daily frequency? what about drugs that are not administered daily? And drugs that are given continuously? 

`validate_prescriptions()` requires a variable called frequency but this is not listed under 'Mandatory fields' in the helpfile. 

In the example for creating ATC_route in the [load data](https://ramses-antibiotics.web.app/articles/load-data.html) vignette the final statement should not be quoted ie `TRUE ~ NA_character_` instead of `TRUE ~ "NA_character_"` or it will be a string instead of a missing value.  Is there a reference for the abbrevations you have in your example in the vignette?

Thanks, 

Emma

**Comment by peterdutey** [comment]
Hi Emma

Thanks for the very relevant issue.

1. All correct. Please note `daily_frequency` can include values between 0 and 1 for meds administered less than daily. Drugs administered continuously is not something I've encountered much other than as PRNs. Can you tell me how they are represented in your hospital's warehouse? These could be coded as PRNs or as dedicated -7 code. More information would be useful.
2. Well spotted!
3. Also well spotted. As for abbreviations, they are documented in the [reference_drug_frequency](https://ramses-antibiotics.web.app/reference/reference_drug_frequency.html) object.

_Tip:_ since you're interested in the data modelling, here's a tip: the complete schema rules are available in CSV files [here](https://github.com/ramses-antibiotics/ramses-package/tree/master/inst/Schema). This can also be found in your machine - the directory path can be found by typing `system.file("Schema", package = "Ramses")` in your R console.

Thanks for reporting those issues/questions. 

On that basis here's what I'm planning for next minor release:

- [ ] add the missing mandatory frequency field in validate_prescription() doc
- [ ] explain the daily_frequency field better in validate_prescription() doc
- [ ] signpost the reference_daily_frequency object in vignette and doc.
- [ ] remove quote marks on load data vignette's `NA_character`
- [ ] deal with drugs administered continuously - more research/info needed.

Peter

**Comment by emmavestesson** [comment]
Hi, 
Thanks for replying so quickly. I checked and continuous is only used for a handful out of more than 400,000 administrations so I'm just going to ignore them.
